services:
  #  Banco de dados
  postgres:
    image: "postgres:16.2-alpine"
    restart: always
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - net-container

  spring-computer-vault-api:
    # image: viniciusgggabriel/spring-computer-vault-api:1.0.0
    build:
      dockerfile: Dockerfile
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB_URL=${POSTGRES_DB_URL}"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres
    networks:
      - net-container

networks:
  net-container:
    driver: bridge